import Foundation
import Testing
@testable import Remember

struct YouTubeTranscriptClientTests {
    @Test(arguments: [
        "https://youtu.be/abcdefghijk",
        "https://www.youtube.com/watch?v=abcdefghijk&feature=share",
        "https://youtube.com/shorts/abcdefghijk",
        "https://m.youtube.com/live/abcdefghijk"
    ])
    func extractsSupportedYouTubeVideoIDs(_ value: String) throws {
        let url = try #require(URL(string: value))
        #expect(YouTubeTranscriptClient.videoID(from: url) == "abcdefghijk")
    }

    @Test func rejectsNonYouTubeAndMalformedVideoIDs() throws {
        let unrelated = try #require(URL(string: "https://example.com/watch?v=abcdefghijk"))
        let malformed = try #require(URL(string: "https://youtube.com/watch?v=short"))
        #expect(YouTubeTranscriptClient.videoID(from: unrelated) == nil)
        #expect(YouTubeTranscriptClient.videoID(from: malformed) == nil)
    }

    @Test func extractsOnlyTheBoundedTimestampedTranscriptSection() {
        let document = """
        # Transcript: Example

        ## Transcript
        [0:01] A grounded opening.
        [0:12] A second idea.
        ---
        Generated by the transcript service.
        """

        #expect(YouTubeTranscriptClient.transcriptSection(in: document) == "[0:01] A grounded opening.\n[0:12] A second idea.")
        #expect(YouTubeTranscriptClient.transcriptSection(in: "## Transcript\nStill generating") == nil)
    }
}
