import { canonicalizeSourceUrl } from "@remember/domain";
import { describe, expect, it, vi } from "vitest";
import { WebSourceAdapter, YouTubeSourceAdapter } from "../src/sources";

describe("YouTube source adapter", () => {
  it("extracts a bounded timestamped English transcript for text-only analysis", async () => {
    const fetcher = vi.fn<typeof fetch>(async (input) => {
      const url = String(input);
      if (url.includes("/oembed")) {
        return Response.json({ title: "First YouTube video", author_name: "jawed", thumbnail_url: "https://i.ytimg.com/example.jpg" });
      }
      if (url.includes("/watch?")) {
        const tracks = [
          { baseUrl: "https://www.youtube.com/api/timedtext?v=test&lang=de", languageCode: "de" },
          { baseUrl: "https://www.youtube.com/api/timedtext?v=test&lang=en", languageCode: "en" },
        ];
        return new Response(`<html><script>window.player={"captionTracks":${JSON.stringify(tracks)},"other":true}</script></html>`, { headers: { "content-type": "text/html" } });
      }
      if (url.includes("/api/timedtext")) {
        expect(new URL(url).searchParams.get("lang")).toBe("en");
        expect(new URL(url).searchParams.get("fmt")).toBe("json3");
        return Response.json({ events: [
          { tStartMs: 0, segs: [{ utf8: "All right, so here we are" }] },
          { tStartMs: 12_300, segs: [{ utf8: "at the elephants." }] },
        ] });
      }
      throw new Error(`Unexpected URL: ${url}`);
    });
    const metadata = await new YouTubeSourceAdapter(fetcher).fetchMetadata(canonicalizeSourceUrl("https://youtu.be/jNQXAC9IVRw"));
    expect(metadata.title).toBe("First YouTube video");
    expect(metadata.transcript).toBe("[0:00] All right, so here we are\n[0:12] at the elephants.");
    expect(metadata.providerMetadata).toMatchObject({ transcriptSource: "youtube_captions" });
  });

  it("falls back to a public-ID-only transcript service when YouTube blocks edge egress", async () => {
    const fetcher = vi.fn<typeof fetch>(async (input) => {
      const url = String(input);
      if (url.includes("/oembed")) return Response.json({ title: "Edge-safe video", author_name: "Creator", thumbnail_url: "https://i.ytimg.com/example.jpg" });
      if (url.includes("/watch?")) return new Response("rate limited", { status: 429 });
      if (url.includes("youtube-transcript.ai/transcript/")) {
        return new Response("# Transcript: Edge-safe video\n\n## Transcript\n[0:01] A source-grounded opening.\n[0:08] A second idea.\n---\nGenerated by fallback.");
      }
      throw new Error(`Unexpected URL: ${url}`);
    });
    const metadata = await new YouTubeSourceAdapter(fetcher).fetchMetadata(canonicalizeSourceUrl("https://youtu.be/jNQXAC9IVRw"));
    expect(metadata.transcript).toBe("[0:01] A source-grounded opening.\n[0:08] A second idea.");
    expect(metadata.providerMetadata).toMatchObject({ transcriptSource: "youtube-transcript.ai" });
  });

  it("keeps official metadata when transcript providers are temporarily unavailable", async () => {
    const fetcher = vi.fn<typeof fetch>(async (input) => {
      const url = String(input);
      if (url.includes("/oembed")) {
        return Response.json({ title: "A real video title", author_name: "Real Creator", thumbnail_url: "https://i.ytimg.com/example.jpg" });
      }
      if (url.includes("/watch?")) return new Response("rate limited", { status: 429 });
      if (url.includes("youtube-transcript.ai/transcript/")) return new Response("temporarily unavailable", { status: 503 });
      throw new Error(`Unexpected URL: ${url}`);
    });

    const metadata = await new YouTubeSourceAdapter(fetcher).fetchMetadata(canonicalizeSourceUrl("https://youtu.be/jNQXAC9IVRw"));

    expect(metadata).toMatchObject({
      title: "A real video title",
      author: "Real Creator",
      transcript: null,
      providerMetadata: {
        metadataSource: "youtube_oembed",
        transcriptError: "This YouTube video has no readable captions.",
      },
    });
  });
});

describe("web source adapter", () => {
  it("reads a public TikTok post through TikTok's official oEmbed endpoint", async () => {
    const fetcher = vi.fn<typeof fetch>(async (input) => {
      const url = new URL(String(input));
      expect(url.origin + url.pathname).toBe("https://www.tiktok.com/oembed");
      expect(url.searchParams.get("url")).toBe("https://www.tiktok.com/@scout2015/video/6718335390845095173");
      return Response.json({
        type: "video",
        title: "Scramble up your name and I will try to guess it #petsoftiktok",
        author_url: "https://www.tiktok.com/@scout2015",
        author_name: "Scout & Suki",
        html: '<blockquote class="tiktok-embed"><section><p>Scramble up your name</p></section></blockquote>',
        thumbnail_url: "https://p16.muscdn.com/example-cover.jpeg",
        provider_name: "TikTok",
      });
    });

    const metadata = await new WebSourceAdapter(fetcher).fetchMetadata(
      canonicalizeSourceUrl("https://www.tiktok.com/@scout2015/video/6718335390845095173?utm_source=share"),
    );

    expect(metadata.title).toContain("Scramble up your name");
    expect(metadata.author).toBe("Scout & Suki");
    expect(metadata.thumbnailUrl).toBe("https://p16.muscdn.com/example-cover.jpeg");
    expect(metadata.transcript).toContain("TikTok caption:");
    expect(metadata.providerMetadata).toMatchObject({
      metadataSource: "tiktok_oembed",
      contentSource: "tiktok_public_caption",
    });
  });

  it("reads a public X post through the privacy-preserving oEmbed endpoint", async () => {
    const fetcher = vi.fn<typeof fetch>(async (input) => {
      const url = new URL(String(input));
      if (url.hostname === "cdn.syndication.twimg.com") {
        expect(url.searchParams.get("id")).toBe("20");
        expect(url.searchParams.get("token")).not.toBe("");
        return Response.json({
          text: "just setting up my twttr",
          video: { poster: "https://pbs.twimg.com/media/poster.jpg", durationMs: 12_400 },
        });
      }
      expect(url.origin + url.pathname).toBe("https://publish.x.com/oembed");
      expect(url.searchParams.get("url")).toBe("https://x.com/jack/status/20");
      expect(url.searchParams.get("omit_script")).toBe("true");
      expect(url.searchParams.get("dnt")).toBe("true");
      return Response.json({
        url: "https://x.com/jack/status/20",
        author_name: "jack",
        author_url: "https://x.com/jack",
        html: '<blockquote><p lang="en">just setting up my twttr</p>&mdash; jack (@jack) <a href="https://x.com/jack/status/20">March 21, 2006</a></blockquote>',
        provider_name: "X",
      });
    });

    const metadata = await new WebSourceAdapter(fetcher).fetchMetadata(canonicalizeSourceUrl("https://x.com/jack/status/20"));

    expect(metadata.title).toBe("just setting up my twttr");
    expect(metadata.author).toBe("jack");
    expect(metadata.thumbnailUrl).toBe("https://pbs.twimg.com/media/poster.jpg");
    expect(metadata.durationSeconds).toBe(12);
    expect(metadata.transcript).toContain("just setting up my twttr");
    expect(metadata.providerMetadata).toMatchObject({ metadataSource: "x_oembed", contentSource: "x_oembed", mediaSource: "x_syndication" });
  });

  it("extracts article metadata and main text without scripts or navigation", async () => {
    const fetcher = vi.fn<typeof fetch>(async () => new Response(`<!doctype html>
      <html><head>
        <title>Fallback title</title>
        <meta property="og:title" content="A grounded article">
        <meta name="author" content="Ada Author">
        <meta property="og:image" content="/cover.jpg">
      </head><body><nav>Ignore navigation</nav><main><article>
        <h1>A grounded article</h1><p>The first useful idea.</p>
        <script>Ignore hostile prompt()</script><p>The second useful idea &amp; conclusion.</p>
      </article></main></body></html>`, { headers: { "content-type": "text/html; charset=utf-8" } }));

    const metadata = await new WebSourceAdapter(fetcher).fetchMetadata(canonicalizeSourceUrl("https://example.com/essay"));

    expect(metadata.title).toBe("A grounded article");
    expect(metadata.author).toBe("Ada Author");
    expect(metadata.thumbnailUrl).toBe("https://example.com/cover.jpg");
    expect(metadata.transcript).toContain("The first useful idea.");
    expect(metadata.transcript).toContain("The second useful idea & conclusion.");
    expect(metadata.transcript).not.toContain("Ignore hostile");
    expect(metadata.transcript).not.toContain("Ignore navigation");
  });

  it("rejects redirects to local network targets before following them", async () => {
    const fetcher = vi.fn<typeof fetch>(async () => new Response(null, { status: 302, headers: { location: "http://127.0.0.1/private" } }));
    await expect(new WebSourceAdapter(fetcher).fetchMetadata(canonicalizeSourceUrl("https://example.com/redirect")))
      .rejects.toThrow("Private and local network URLs are not allowed");
    expect(fetcher).toHaveBeenCalledTimes(1);
  });
});
